# Generated by Django 2.0.7 on 2018-07-21 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0002_auto_20180718_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepOne', models.CharField(max_length=100)),
                ('stepTwo', models.CharField(max_length=100)),
                ('stepThree', models.CharField(max_length=100)),
                ('recipeKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life.Recipe')),
            ],
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
